export const APPOINTMENT_FETCH_REQUEST = 'APPOINTMENT_FETCH_REQUEST'
export const APPOINTMENT_FETCH_SUCCESS = 'APPOINTMENT_FETCH_SUCCESS'
export const APPOINTMENT_FETCH_FAIL = 'APPOINTMENT_FETCH_FAIL'
export const APPOINTMENT_FETCH_RESET = 'APPOINTMENT_FETCH_RESET'


export const MEDICINELIST_FETCH_REQUEST = 'MEDICINELIST_FETCH_REQUEST'
export const MEDICINELIST_FETCH_SUCCESS = 'MEDICINELIST_FETCH_SUCCESS'
export const MEDICINELIST_FETCH_FAIL = 'MEDICINELIST_FETCH_FAIL'
export const MEDICINELIST_FETCH_RESET = 'MEDICINELIST_FETCH_RESET'

export const TESTLIST_FETCH_REQUEST = 'TESTLIST_FETCH_REQUEST'
export const TESTLIST_FETCH_SUCCESS = 'TESTLIST_FETCH_SUCCESS'
export const TESTLIST_FETCH_FAIL = 'TESTLIST_FETCH_FAIL'
export const TESTLIST_FETCH_RESET = 'TESTLIST_FETCH_RESET'

export const TESTPRESC_FETCH_REQUEST = 'TESTPRESC_FETCH_REQUEST'
export const TESTPRESC_FETCH_SUCCESS = 'TESTPRESC_FETCH_SUCCESS'
export const TESTPRESC_FETCH_FAIL = 'TESTPRESC_FETCH_FAIL'
export const TESTPRESC_FETCH_RESET = 'TESTPRESC_FETCH_RESET'

export const MEDPRESC_FETCH_REQUEST = 'MEDPRESC_FETCH_REQUEST'
export const MEDPRESC_FETCH_SUCCESS = 'MEDPRESC_FETCH_SUCCESS'
export const MEDPRESC_FETCH_FAIL = 'MEDPRESC_FETCH_FAIL'
export const MEDPRESC_FETCH_RESET = 'MEDPRESC_FETCH_RESET'