export const EMPLOYEE_SIGNIN_REQUEST = "EMPLOYEE_SIGNIN_REQUEST";
export const EMPLOYEE_SIGNIN_SUCCESS = "EMPLOYEE_SIGNIN_SUCCESS";
export const EMPLOYEE_SIGNIN_FAIL = "EMPLOYEE_SIGNIN_FAIL";
export const EMPLOYEE_SIGNOUT = "EMPLOYEE_SIGNOUT";

export const EMPLOYEE_SIGNUP_REQUEST = "EMPLOYEE_SIGNUP_REQUEST";
export const EMPLOYEE_SIGNUP_SUCCESS = "EMPLOYEE_SIGNUP_SUCCESS";
export const EMPLOYEE_SIGNUP_FAIL = "EMPLOYEE_SIGNUP_FAIL";

export const EMPLOYEE_VIEWEMPLOYEES_REQUEST = "EMPLOYEE_VIEWEMPLOYEES_REQUEST";
export const EMPLOYEE_VIEWEMPLOYEES_SUCCESS = "EMPLOYEE_VIEWEMPLOYEES_SUCCESS";
export const EMPLOYEE_VIEWEMPLOYEES_FAIL = "EMPLOYEE_VIEWEMPLOYEES_FAIL";

export const EMPLOYEE_DELETE_REQUEST = "EMPLOYEE_DELETE_REQUEST";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL";

export const EMPLOYEE_UPDATE_REQUEST = "EMPLOYEE_UPDATE_REQUEST";
export const EMPLOYEE_UPDATE_SUCCESS = "EMPLOYEE_UPDATE_SUCCESS";
export const EMPLOYEE_UPDATE_FAIL = "EMPLOYEE_UPDATE_FAIL";

export const ADMIN_GET_ALL_CHARGES_REQUEST = "ADMIN_GET_ALL_CHARGES_REQUEST";
export const ADMIN_GET_ALL_CHARGES_SUCCESS = "ADMIN_GET_ALL_CHARGES_SUCCESS";
export const ADMIN_GET_ALL_CHARGES_FAIL = "ADMIN_GET_ALL_CHARGES_FAIL";
