export const PATIENT_SIGNIN_REQUEST = 'PATIENT_SIGNIN_REQUEST'
export const PATIENT_SIGNIN_SUCCESS = 'PATIENT_SIGNIN_SUCCESS'
export const PATIENT_SIGNIN_FAIL = 'PATIENT_SIGNIN_FAIL'
export const PATIENT_SIGNOUT = 'PATIENT_SIGNOUT'

export const PATIENT_SIGNUP_REQUEST = 'PATIENT_SIGNUP_REQUEST'
export const PATIENT_SIGNUP_SUCCESS = 'PATIENT_SIGNUP_SUCCESS'
export const PATIENT_SIGNUP_FAIL = 'PATIENT_SIGNUP_FAIL'

export const PATIENT_GET_DOC_REQUEST="PATIENT_GET_DOC_REQUEST"
export const PATIENT_GET_DOC_SUCCESS="PATIENT_GET_DOC_SUCCESS"
export const PATIENT_GET_DOC_FAIL="PATIENT_GET_DOC_FAIL"

export const PATIENT_BOOK_Appointment_REQUEST="PATIENT_BOOK_Appointment_REQUEST"
export const PATIENT_BOOK_Appointment_SUCCESS="PATIENT_BOOK_Appointment_SUCCESS"
export const PATIENT_BOOK_Appointment_FAIL="PATIENT_BOOK_Appointment_FAIL"

export const PATIENT_EDIT_PROFILE_REQUEST="PATIENT_EDIT_PROFILE_REQUEST"
export const PATIENT_EDIT_PROFILE_SUCCESS="PATIENT_EDIT_PROFILE_SUCCESS"
export const PATIENT_EDIT_PROFILE_FAIL="PATIENT_EDIT_PROFILE_FAIL"

export const PATIENT_GET_PROFILE_REQUEST="PATIENT_GET_PROFILE_REQUEST"
export const PATIENT_GET_PROFILE_SUCCESS="PATIENT_GET_PROFILE_SUCCESS"
export const PATIENT_GET_PROFILE_FAIL="PATIENT_GET_PROFILE_FAIL"

export const PATIENT_VIEW_PRESC_REQUEST = 'PATIENT_VIEW_PRESC_REQUEST'
export const PATIENT_VIEW_PRESC_SUCCESS = 'PATIENT_VIEW_PRESC_SUCCESS'
export const PATIENT_VIEW_PRESC_FAIL = 'PATIENT_VIEW_PRESC_FAIL'