export const RECP_GET_DOCTORS_REQUEST = "RECP_GET_DOCTORS_REQUEST";
export const RECP_GET_DOCTORS_SUCCESS = "RECP_GET_DOCTORS_SUCCESS";
export const RECP_GET_DOCTORS_FAIL = "RECP_GET_DOCTORS_FAIL";

export const RECP_VIEW_APPOINTMENTS_REQUEST = "RECP_VIEW_APPOINTMENTS_REQUEST";
export const RECP_VIEW_APPOINTMENTS_SUCCESS = "RECP_VIEW_APPOINTMENTS_SUCCESS";
export const RECP_VIEW_APPOINTMENTS_FAIL = "RECP_VIEW_APPOINTMENTS_FAIL";
export const RECP_VIEW_APPOINTMENTS_RESET = "RECP_VIEW_APPOINTMENTS_RESET";

export const RECP_ALL_APPOINTMENTS_REQUEST = "RECP_ALL_APPOINTMENTS_REQUEST";
export const RECP_ALL_APPOINTMENTS_SUCCESS = "RECP_ALL_APPOINTMENTS_SUCCESS";
export const RECP_ALL_APPOINTMENTS_FAIL = "RECP_ALL_APPOINTMENTS_FAIL";
export const RECP_ALL_APPOINTMENTS_RESET = "RECP_ALL_APPOINTMENTS_RESET";

export const RECP_ADMIT_PATIENT_REQUEST = "RECP_ADMIT_PATIENT_REQUEST";
export const RECP_ADMIT_PATIENT_SUCCESS = "RECP_ADMIT_PATIENT_SUCCESS";
export const RECP_ADMIT_PATIENT_FAIL = "RECP_ADMIT_PATIENT_FAIL";

export const RECP_GET_ADMIT_PATIENT_REQUEST = "RECP_GET_ADMIT_PATIENT_REQUEST";
export const RECP_GET_ADMIT_PATIENT_SUCCESS = "RECP_GET_ADMIT_PATIENT_SUCCESS";
export const RECP_GET_ADMIT_PATIENT_FAIL = "RECP_GET_ADMIT_PATIENT_FAIL";

export const RECP_DISCHARGE_PATIENT_REQUEST = "RECP_DISCHARGE_PATIENT_REQUEST";
export const RECP_DISCHARGE_PATIENT_SUCCESS = "RECP_DISCHARGE_PATIENT_SUCCESS";
export const RECP_DISCHARGE_PATIENT_FAIL = "RECP_DISCHARGE_PATIENT_FAIL";

export const RECP_MAKE_PAYMENT_REQUEST = "RECP_MAKE_PAYMENT_REQUEST";
export const RECP_MAKE_PAYMENT_SUCCESS = "RECP_MAKE_PAYMENT_SUCCESS";
export const RECP_MAKE_PAYMENT_FAIL = "RECP_MAKE_PAYMENT_FAIL";
